In [3]:
print('Hello Numpy')

Hello Numpy


In [4]:
2+8*5

42

###This is a basic text  markdown

In [5]:
import numpy as np

In [8]:
integer=np.array([10,20,30,40,50])

In [9]:
print(integer)

[10 20 30 40 50]


In [10]:
integer[2]

30

In [12]:
integer[3:]

array([40, 50])

In [13]:
integer[0]=21.5

In [14]:
integer

array([21, 20, 30, 40, 50])

In [15]:
integer.dtype

dtype('int32')

In [17]:
smallerinteger=np.array(integer,dtype=np.int8)
smallerinteger

array([21, 20, 30, 40, 50], dtype=int8)

In [22]:
integer.nbytes

20

In [21]:
smallerinteger.nbytes

5

In [29]:
overflow=np.array([127,128,129],dtype=np.int8)
overflow

C:\Users\91808\AppData\Local\Temp\ipykernel_17020\2481175571.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  overflow=np.array([127,128,129],dtype=np.int8)
C:\Users\91808\AppData\Local\Temp\ipykernel_17020\2481175571.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  overflow=np.array([127,128,129],dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [31]:
floata=np.array([1,2,2,3,3,4,5,1,8,3])
print(floata)

[1 2 2 3 3 4 5 1 8 3]


In [32]:
floata.dtype

dtype('int32')

In [ ]:
#Multidimensional array

In [33]:
import numpy as np

In [35]:
numa=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2Dimensional array
numa

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
numa[1,2]#to access a particular element

8

In [40]:
numa.ndim

2

In [41]:
numb=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) #3Dimensional array
numb

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [42]:
numc=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]]) #2-2Dimensional array
numc

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [45]:
numc[1,0,2]

13

In [46]:
numc[0,1,4]

10

In [47]:
#creating arrays from Lists and other python structures
import numpy as np

In [48]:
first_list=[1,2,3,4,5,6,7,8,9,10]

In [49]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [51]:
first_array=np.array(first_list)

In [52]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
second_list=[1,2,3,-1.23,50,128000,56,4.56]

In [54]:
second_list

[1, 2, 3, -1.23, 50, 128000, 56, 4.56]

In [55]:
second_array=np.array(second_list)

In [56]:
second_array

array([ 1.00e+00,  2.00e+00,  3.00e+00, -1.23e+00,  5.00e+01,  1.28e+05,
        5.60e+01,  4.56e+00])

In [57]:
second_array.dtype

dtype('float64')

In [58]:
first_array.dtype

dtype('int32')

In [59]:
first_array.ndim

1

In [60]:
second_array.ndim

1

In [61]:
third_list=['ANN',121000,'Peter',156431,'Susan',154523,'John',144569]

In [62]:
third_list

['ANN', 121000, 'Peter', 156431, 'Susan', 154523, 'John', 144569]

In [63]:
third_array=np.array(third_list)

In [64]:
third_array #here all the elements become strings

array(['ANN', '121000', 'Peter', '156431', 'Susan', '154523', 'John',
       '144569'], dtype='<U11')

In [65]:
first_tuple=[5,10,15,20,25,30]

In [66]:
first_tuple

[5, 10, 15, 20, 25, 30]

In [67]:
array_from_tuple=np.array(first_tuple)

In [68]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [69]:
array_from_tuple.dtype

dtype('int32')

In [71]:
muti_dim_list=[[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]]

In [72]:
muti_dim_list

[[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]]

In [73]:
array_from_muti_dim_list=np.array(muti_dim_list)

In [74]:
array_from_muti_dim_list

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]])

In [75]:
#intrinsic Numpy array creation to quickly generate an array
import numpy as np

In [78]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [82]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [83]:
#if we want to create an array of floating points having evenly spaced decimal values
#numpy.linspace
first_float_array=np.linspace(10,30) #its only one dimensional
first_float_array

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [84]:
#arrange will take the third arguments as the setsize and linspace will give the number of points you want
Second_float_array=np.linspace(10,30,5)
Second_float_array

array([10., 15., 20., 25., 30.])

In [85]:
First_rand_arr=np.random.rand(10)

In [86]:
First_rand_arr

array([0.5988758 , 0.94137343, 0.71730877, 0.63422326, 0.40858013,
       0.25177213, 0.68106648, 0.45490476, 0.13848373, 0.44963928])

In [90]:
second_rand_arr=np.random.rand(4,5)
second_rand_arr

array([[0.35455364, 0.30874512, 0.29532323, 0.93109672, 0.63621114],
       [0.76110885, 0.98114121, 0.58598926, 0.38066516, 0.83346413],
       [0.27458443, 0.57736905, 0.465379  , 0.15143686, 0.43357446],
       [0.55374762, 0.25164999, 0.94536803, 0.29302874, 0.05318614]])

In [91]:
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([84,  8, 22, 53, 74, 19, 35, 47, 12, 93, 60, 95,  3,  5,  4, 84, 84,
       71, 59, 89])

In [94]:
#creating arrays filled with constant values
first_z_array=np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [98]:
second_z_array=np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
first_ones_array=np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [101]:
first_ones_array=np.ones((5,6))
first_ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [104]:
third_ones_array=np.ones((5,6),dtype=str)
third_ones_array

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [105]:
third_ones_array=np.ones((5,6),dtype=float)
third_ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [106]:
third_ones_array=np.ones((5,6),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [108]:
first_fill_array=np.empty((10),dtype=int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [109]:
first_full_array=np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [112]:
second_full_array=np.full((5,10),8)
second_full_array

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [113]:
#Find the size and shape of an array
import numpy as np

In [115]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [117]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [118]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [119]:
np.shape(first_arr)

(20,)

In [120]:
np.shape(second_arr)

(10, 2)

In [121]:
np.shape(third_arr)

(2, 2, 2)

In [122]:
np.size(first_arr)

20

In [123]:
np.size(second_arr)

20

In [124]:
np.size(third_arr)

8

In [126]:
multi_DArray = np.array( [ [ [1,2,3,4,5], [5,4,3,2,1] ],[ [6,7,8,9,10], [10,9,8,7,6] ] ] )
multi_DArray[1, 0, 2]

8

In [128]:
array1 = [ 'WA' , 24, 'CA', 'NH', 564]
array2 = np.array(array1)
array2

array(['WA', '24', 'CA', 'NH', '564'], dtype='<U11')

In [129]:
array1 = np.array( [1,2,3,4,5], dtype=np.int64)
array2 = np.array( [1,2,3,4,5], dtype=np.int8)

In [130]:
array1.dtype

dtype('int64')

In [131]:
np.array([50, 60, 70, 80, 90,100])

array([ 50,  60,  70,  80,  90, 100])

In [134]:
integers=np.array([1,2,3,4,5])
integers[2]

3

In [146]:
#adding removing and sorting elements
first_arr=np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [144]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [143]:
new1_first_arr=np.append(first_arr,6)
new1_first_arr

array([1, 2, 3, 5, 6])

In [149]:
first_arr=np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [150]:
del_arr=np.delete(first_arr,2)
del_arr

array([1, 2, 5])

In [161]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([13,  5, 15,  1,  9,  4, 15, 18,  2,  9, 15,  1, 16, 10,  8,  4,  4,
       17,  6,  4])

In [162]:
print(np.sort(integers_arr))

[ 1  1  2  4  4  4  4  5  6  8  9  9 10 13 15 15 15 16 17 18]


In [163]:
integers_2dim_arr=np.array([[3,2,5,7,4],[5,0,8,3,1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [164]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [166]:
colors=np.array(['orange','yellow','white','blue','green','red'])
colors

array(['orange', 'yellow', 'white', 'blue', 'green', 'red'], dtype='<U6')

In [167]:
print(np.sort(colors))

['blue' 'green' 'orange' 'red' 'white' 'yellow']


In [169]:
#copy is a new array and view is a different view of original array
std_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
std_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [170]:
std_ids_number_reg=std_ids_number
print("ids of std_id_number",id(std_ids_number))
print("ids of std_id_number_reg",id(std_ids_number_reg))

ids of std_id_number 1521443528720
ids of std_id_number_reg 1521443528720


In [171]:
std_ids_number_reg[1]=2222

In [172]:
std_ids_number_reg

array([1111, 2222, 1313, 1414, 1515, 1616, 1717, 1818])

In [173]:
std_ids_number

array([1111, 2222, 1313, 1414, 1515, 1616, 1717, 1818])

In [174]:
print(std_ids_number) #any change in one will reflect on the other one too
print(std_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [175]:
std_ids_number_cp=std_ids_number.copy()

In [176]:
std_ids_number_cp

array([1111, 2222, 1313, 1414, 1515, 1616, 1717, 1818])

In [177]:
print(std_ids_number)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [179]:
print(std_ids_number_cp==std_ids_number)

[ True  True  True  True  True  True  True  True]


In [180]:
print("ids of std_id_number",id(std_ids_number))
print("ids of std_id_number_reg",id(std_ids_number_cp))

ids of std_id_number 1521443528720
ids of std_id_number_reg 1521445975984


In [183]:
std_ids_number_reg[0]=1000
print("original",std_ids_number)
print("copy",std_ids_number_cp)

original [1000 2222 1313 1414 1515 1616 1717 1818]
copy [1111 2222 1313 1414 1515 1616 1717 1818]


In [184]:
#view
std_ids_number_v=std_ids_number.view()

In [189]:
std_ids_number_v[0]=2000
print("original",std_ids_number)
print("view",std_ids_number_v)

original [2000 2222 1313 1414 1515 1616 1717 1818]
view [2000 2222 1313 1414 1515 1616 1717 1818]


In [190]:
print(std_ids_number_cp.base)
print("view",std_ids_number_v.base)

None
view [2000 2222 1313 1414 1515 1616 1717 1818]


In [191]:
#reshaping
#no of elements remains same and shape of array changes
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [192]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [194]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [197]:
fourth_arr=np.reshape(first_arr(4,4))

TypeError: 'numpy.ndarray' object is not callable

In [202]:
fifth_arr = np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print("dimension of fifth_arr is", fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
dimension of fifth_arr is 3


In [203]:
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [204]:
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [208]:
#flatten:return a copy in one Dimension
eight_arr_flat=sixth_arr.flatten()
print("eight_arr_flat",eight_arr_flat)
ninth_arr_rev=sixth_arr.ravel()
print("ninth_arr_rev", ninth_arr_rev)

eight_arr_flat [1 2 3 4 5 6]
ninth_arr_rev [1 2 3 4 5 6]


In [210]:
eight_arr_flat[0]=100

In [211]:
ninth_arr_rev[0]=200

In [212]:
print("eight_arr_flat",eight_arr_flat)
print("ninth_arr_rev", ninth_arr_rev)
print("sixth_arr", sixth_arr)

eight_arr_flat [100   2   3   4   5   6]
ninth_arr_rev [200   2   3   4   5   6]
sixth_arr [[200   2]
 [  3   4]
 [  5   6]]


In [213]:
#indexing and slicing
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [214]:
twodim_arr[1,1]

5

In [215]:
twodim_arr[1]

array([4, 5, 6, 7])

In [216]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [217]:
threedim_arr[0,2,3]

13

In [218]:
threedim_arr[2,-1,-1]

59

In [219]:
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [223]:
onedim_arr[:6]

array([0, 1, 2, 3, 4, 5])

In [224]:
onedim_arr[-4]

6

In [225]:
onedim_arr[-4:]

array([6, 7, 8, 9])

In [226]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [227]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [228]:
twodim_arr[1 :,1 :]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [230]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [231]:
twodim_arr[:,2]

array([ 2,  6, 10])

In [235]:
#functions for joining arrays
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print(first_arr)
print(second_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [239]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [241]:
third_2darr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
third_2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [242]:
four_2darr=np.array([[11,12,13,14,15],[16,17,18,19,20]])
four_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [246]:
con2d_arr=np.concatenate((third_2darr,four_2darr))
con2d_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [247]:
con2d_arr=np.concatenate((third_2darr,four_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [248]:
st_arr=np.stack((first_arr,second_arr))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [249]:
horizontal_arr=np.hstack((first_arr,second_arr))
horizontal_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [250]:
vertical_arr=np.vstack((first_arr,second_arr))
vertical_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [252]:
#functions for splitting arrays
#split
#array_split
#hsplit
#vsplit
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [255]:
split_arr=np.array_split(first_arr,4)
split_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [256]:
split_arr=np.split(first_arr,4)
split_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [257]:
print(split_arr[1])

[4 5 6]


In [259]:
split_arr=np.array_split(first_arr,8)
split_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [262]:
h_split=np.hsplit(third_2darr,5)
h_split

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [264]:
v_split=np.vsplit(third_2darr,2)
v_split

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

In [267]:
arr = np.array([2,4,6,8])
new_array = np.insert (arr, 2, 10) 
new_array

array([ 2,  4, 10,  6,  8])

In [266]:
arr = np.array([2,4,6,8])
new_array = np.append (arr, 10)
new_array

array([ 2,  4,  6,  8, 10])

In [268]:
arr = np.array([2,4,6,8,10,12,14,16,18,20])
new_arr = np.reshape(arr, (2, 5))
new_arr

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [271]:
arr = np.array([2,4,6,8,10])
arr[1:2:3]

array([4])

In [3]:
#arithematic operations and functions
import numpy as np
a=np.arange(1,11)
b=np.arange(21,31)
print('a',a)
print('b',b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [4]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [5]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [6]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [7]:
a/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [8]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [12]:
c=np.arange(2,12)
print("c",c)

c [ 2  3  4  5  6  7  8  9 10 11]


In [13]:
a**c

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [14]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [17]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [18]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [19]:
np.divide(a,b)

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [20]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [24]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [25]:
np.power(a,c)

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [26]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [27]:
#Broadcasting
#the term describes how numpy treats arrays with different shapes during arithmatic operations
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [29]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [30]:
c=np.arange(1,3)

In [31]:
c

array([1, 2])

In [32]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [33]:
d=np.arange(24).reshape(2,3,4)

In [34]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [36]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

In [37]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [38]:
#aggregate functions
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [53]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [42]:
first_arr.sum()

550

In [43]:
second_arr.sum()

450

In [44]:
third_arr.sum()

550

In [45]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [46]:
third_arr.sum(axis=0)

array([ 70,  90, 110, 130, 150])

In [47]:
first_arr.sum(axis=0)

550

In [48]:
first_arr.prod()

1704722432

In [54]:
second_arr.prod()

-1786839040

In [52]:
third_arr.prod()

1704722432

In [55]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [56]:
np.average(first_arr)

55.0

In [57]:
np.average(second_arr)

50.0

In [58]:
np.average(third_arr)

55.0

In [59]:
np.min(first_arr)

10

In [60]:
np.min(second_arr)

10

In [61]:
np.min(third_arr)

10

In [62]:
np.max(first_arr)

100

In [63]:
np.max(second_arr)

90

In [64]:
np.max(third_arr)

100

In [65]:
np.mean(first_arr)

55.0

In [66]:
np.std(first_arr)

28.722813232690143

In [69]:
#how to get unique items and counts
first_arr=np.array([1,2,3,4,5,6,1,4,5,7,8,9,3,5])
np.unique(first_arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
second_arr=np.array([[1,2,1,1],[3,4,5,6],[1,4,5,7],[8,9,3,5]])
np.unique(second_arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.unique(second_arr,axis=0)

array([[1, 2, 1, 1],
       [1, 4, 5, 7],
       [3, 4, 5, 6],
       [8, 9, 3, 5]])

In [72]:
np.unique(second_arr,axis=0)

array([[1, 2, 1, 1],
       [1, 4, 5, 7],
       [3, 4, 5, 6],
       [8, 9, 3, 5]])

In [73]:
np.unique(first_arr,return_index=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4,  5,  9, 10, 11], dtype=int64))

In [74]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([4, 1, 2, 2, 3, 1, 1, 1, 1], dtype=int64))

In [77]:
#transpose like operations
first_2dimarr=np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [79]:
second_2dimarr=np.arange(6).reshape((3,2))
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [82]:
np.transpose(second_2dimarr)

array([[0, 2, 4],
       [1, 3, 5]])

In [83]:
first_3dimarr=np.arange(24).reshape((2,3,4))
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [84]:
np.moveaxis(first_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [86]:
np.swapaxes(first_3dimarr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [87]:
#reverse an array
#reverse an array using slicing
arr_1dim=[10,1,2,4,5,6,7,8,9,4]
arr_1dim

[10, 1, 2, 4, 5, 6, 7, 8, 9, 4]

In [89]:
arr_1dim[::-1]

[4, 9, 8, 7, 6, 5, 4, 2, 1, 10]

In [90]:
np.flip(arr_1dim)

array([ 4,  9,  8,  7,  6,  5,  4,  2,  1, 10])

In [93]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [96]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [97]:
arr_3dim=np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [99]:
np.flip(arr_3dim,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

In [100]:
np.logspace(1, 3, 5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])